### PR TITLE
V1.2 Update

### LINKED ISSUE #6: Clean Up Categorization
RCS sound files should be organised into folders in the mod, to save time and clean up the file system, making it easier to find certain songs.

*e.g.* **ACTION** songs go into a mod folder called **ACTION**, with the `config.cpp` outside of it.

- [x] ACTION
- [x] RELAX
- [x] STEALTH
- [x] SAD
- [x] MISC

### LINKED ISSUE #11: Clean Up Songs
Revamp some existing songs that aren't up to the highest quality:

**Improve:**
**Lost But Won - ACTION:** [Suggestion Song](https://youtu.be/kOYcbod5J0w) 

**Remove:**
- Restless *(RELAX)*
- Daybreak *(RELAX)*

### PR DESCRIPTION
**Pull request by Radiumio**
Added categorisation of all songs, courtesy of @SDTheCyanWyan

### CODE REVIEW

**Review by Radiumio — COMMENTED** [review]
Was not able to find any other issues going over it a second time.

**Comment by Radiumio** [comment]
@SDTheCyanWyan Please review the **entire** `config.cpp` when you can, and review for mistakes carefully.

**Review by Ryan180602 — APPROVED** [review]
Have checked `config.cpp` in it's entirety. `RCS_madameExecutioner.ogg` was duplicated in `SAD` and `MISC`. Have deleted the copy in `MISC`.

**Comment by Radiumio** [comment]
Will pack and test branch **before** merging and releasing.

**Comment by Radiumio** [comment]
> **Do not merge!**
> 
> There is a bug with *lostButWon*, according to RPT it cannot be read. Will need to fix this before merging, worst case we remove the song.

This should be fixed.

**Pull request merged**
